### ISSUE TITLE
Contact section fade up trigger

### ISSUE THREAD

**Issue by Tursko** [UTSA-ACM/acmutsa.github.io#15]
The contact section's 'fade-up' animation doesn't trigger when you expect it to. 

I would expect it to display at this point:
![image](https://user-images.githubusercontent.com/18274896/133683368-35cce2db-8363-4dd9-b727-553fd56b33d4.png)

But it doesn't fade in until I hit the footer, so I don't even see the "Contact" header:
![image](https://user-images.githubusercontent.com/18274896/133683663-2ff99d80-23d4-4af7-92e6-a4b5b4582d94.png)

Referenced files:
https://github.com/UTSA-ACM/acmutsa.github.io/blob/main/index.html
https://github.com/UTSA-ACM/acmutsa.github.io/blob/main/_includes/contact_section.html

**Comment by Zaqttack** [comment]
Oh! Nice catch. I can take some time this next week and figure it out. I think it's something to do with how Jekyll is templating the data-aos attribute. Not 100% sure tho.
